sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yaoshuaixiang
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzyPd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx5eb8295382fdbb1a
    secret: 44ebc8706bf9c0e121404700dd11a863
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://1750d3c5.r20.cpolar.top//wxpay/pay.php
    refundNotifyUrl: https://1750d3c5.r20.cpolar.top//wxpay/pay.php
